# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 310b089f22782c4d3e10f83cfcfc706cb7c24489d5295703304e236d8f4eec60d57937a3c94bdfa0f55af853265a1d204b04dc743f3bfa5c92aad1c605053fbe

test:
  secret_key_base: f215abc4f63bc2b47390a24dcb2eb1252dc7edb0d18f8ba3d68914c27f5258427f20a5ae799368bee6b556d11d71fe8913d0d0d68432193d582e664ea405e137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
